@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Oct 23 17:55:44 -0700 2020
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim lab2_7Seg_testbench_behav -key {Behavioral:sim_1:Functional:lab2_7Seg_testbench} -tclbatch lab2_7Seg_testbench.tcl -view C:/Users/Simon/Desktop/CSE100/Lab2/sfcCSE100Lab2.xpr/sfcCSE100Lab2/sfcCSE100Lab2.srcs/sim_1/imports/sfcCSE100Lab2/lab2_7Seg_testbench_behav.wcfg -log simulate.log"
call xsim  lab2_7Seg_testbench_behav -key {Behavioral:sim_1:Functional:lab2_7Seg_testbench} -tclbatch lab2_7Seg_testbench.tcl -view C:/Users/Simon/Desktop/CSE100/Lab2/sfcCSE100Lab2.xpr/sfcCSE100Lab2/sfcCSE100Lab2.srcs/sim_1/imports/sfcCSE100Lab2/lab2_7Seg_testbench_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
